package com.ckula.mangafoxdownloader.model;

import java.util.Set;
import java.util.TreeSet;

import com.ckula.mangafoxdownloader.utils.StringUtils;
import com.google.gson.annotations.Expose;
import com.google.gson.annotations.SerializedName;

public class Manga {

    @SuppressWarnings("unused")
    private final String WARNING = "THIS FILE IS AUTOMATICALLY GENERATED. DON'T EDIT IT MANUALLY";

    private String name;
    private transient String urlName;
    private boolean completed = false;
    private boolean licensed = false;

    private String link;
    @Expose
    @SerializedName("xml_link")
    private String xmlLink;

    private Set<Chapter> chapters;

    public Manga(String name) {
	this.name = name;
	this.urlName = StringUtils.transformToMangaFoxUrlName(name);
	this.chapters = new TreeSet<Chapter>();

	this.link = "http://mangafox.me/manga/" + this.urlName;
	this.xmlLink = "http://mangafox.me/rss/" + this.urlName + ".xml";
    }

    public Set<Chapter> getChapters() {
	return chapters;
    }

    public void setChapters(Set<Chapter> chapters) {
	this.chapters = chapters;
    }

    public boolean isCompleted() {
	return completed;
    }

    public void setCompleted(boolean completed) {
	this.completed = completed;
    }

    public String getName() {
	return name;
    }

    public void setName(String name) {
	this.name = name;
    }

    public String getUrlName() {
	return urlName;
    }

    public void setUrlName(String urlName) {
	this.urlName = urlName;
    }

    public boolean isLicensed() {
	return licensed;
    }

    public void setLicensed(boolean licensed) {
	this.licensed = licensed;
    }

    public String getLink() {
	return link;
    }

    public void setLink(String link) {
	this.link = link;
    }

    public String getXmlLink() {
	return xmlLink;
    }

    public void setXmlLink(String xmlLink) {
	this.xmlLink = xmlLink;
    }

    public boolean hasThisChapter(Chapter chapter) {
	boolean hasThisChapter = false;
	for (Chapter c : this.chapters) {
	    if (chapter.equals(c)) {
		hasThisChapter = true;
		break;
	    }
	}
	return hasThisChapter;
    }
}
